name: Publish to docker hub
on:
  workflow_dispatch:
    inputs:
      image_version:
        type: string

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and release
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64,linux/amd64
          tags: mergermarket/c6-mono-runtime:${{ inputs.image_version }},mergermarket/c6-mono-runtime:latest
          push: true
          context: .
